#pragma once

namespace Game
{
	enum ComponentType
	{
		COMPONENT = 0x0001,
		SCENE_COMPONENT = 0x0002,

		PRIMITIVE_COMPONENT = (SCENE_COMPONENT | 0x0001),
		COLLISION_COMPONENT = (SCENE_COMPONENT | 0x0010),
		SKYBOX_COMPONENT = (PRIMITIVE_COMPONENT | 0x0100),
		STATIC_MESH_COMPONENT = (PRIMITIVE_COMPONENT | 0x1000)
	};
}
